# Generated by Django 4.2.1 on 2023-05-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
